enum PromotionType {
  STORY_PROMOTION = "STORY_PROMOTION",
  FEED_PROMOTION = "FEED_PROMOTION",
  LIVE_PROMOTION = "LIVE_PROMOTION",
  USER_GENERATED_CONTENT = "USER_GENERATED_CONTENT",
  ADD_REVIEWS = "ADD_REVIEWS",
}
enum CollaborationType {
  PAID = "PAID",
  UNPAID = "UNPAID",
}
enum SocialPlatform {
  FACEBOOK = "FACEBOOK",
  INSTAGRAM = "INSTAGRAM",
  YOUTUBE = "YOUTUBE",
  TWITTER = "TWITTER",
  OTHERS = "OTHERS",
}

export const collaborationsData = [
  {
    name: "Fashion Campaign This is",
    description: "Collaboration for promoting new fashion products",
    timeStamp: Date.now(),
    budget: { min: 1000, max: 5000 },
    location: {
      type: "physical",
      name: "Paris",
      latlong: { lat: 48.8566, lng: 2.3522 },
    },
    promotionType: PromotionType.FEED_PROMOTION,
    collaborationType: CollaborationType.PAID,
    platform: SocialPlatform.INSTAGRAM,
    numberOfInfluencersNeeded: 3,
    externalLinks: ["https://example.com/fashion"],
    viewsLastHour: 100,
    lastReviewedTimeStamp: null,
  },
  {
    name: "Tech Review Showcase",
    description: "Showcase the latest tech gadgets with influencer reviews",
    timeStamp: Date.now(),
    budget: { min: 2000, max: 7000 },
    location: {
      type: "physical",
      name: "San Francisco",
      latlong: { lat: 37.7749, lng: -122.4194 },
    },
    promotionType: PromotionType.USER_GENERATED_CONTENT,
    collaborationType: CollaborationType.UNPAID,
    platform: SocialPlatform.YOUTUBE,
    numberOfInfluencersNeeded: 5,
    externalLinks: ["https://example.com/techreview"],
    viewsLastHour: 250,
    lastReviewedTimeStamp: null,
  },
  {
    name: "Luxury Travel Blog Promotion",
    description: "Promote luxury resorts through blog and feed posts",
    timeStamp: Date.now(),
    budget: { min: 5000, max: 15000 },
    location: {
      type: "virtual",
      name: "Global",
      latlong: null,
    },
    promotionType: PromotionType.STORY_PROMOTION,
    collaborationType: CollaborationType.PAID,
    platform: SocialPlatform.FACEBOOK,
    numberOfInfluencersNeeded: 2,
    externalLinks: ["https://example.com/luxurytravel"],
    viewsLastHour: 300,
    lastReviewedTimeStamp: Date.now(),
  },
  {
    name: "Eco-Friendly Lifestyle Campaign",
    description: "Spread awareness about eco-friendly lifestyle practices",
    timeStamp: Date.now(),
    budget: { min: 800, max: 2000 },
    location: {
      type: "virtual",
      name: "Global",
      latlong: null,
    },
    promotionType: PromotionType.LIVE_PROMOTION,
    collaborationType: CollaborationType.UNPAID,
    platform: SocialPlatform.TWITTER,
    numberOfInfluencersNeeded: 4,
    externalLinks: ["https://example.com/ecofriendly"],
    viewsLastHour: 120,
    lastReviewedTimeStamp: null,
  },
  {
    name: "Fitness Brand Influencer Collab",
    description: "Promote fitness gear with influencer partnerships",
    timeStamp: Date.now(),
    budget: { min: 1500, max: 4000 },
    location: {
      type: "physical",
      name: "New York City",
      latlong: { lat: 40.7128, lng: -74.006 },
    },
    promotionType: PromotionType.FEED_PROMOTION,
    collaborationType: CollaborationType.PAID,
    platform: SocialPlatform.INSTAGRAM,
    numberOfInfluencersNeeded: 6,
    externalLinks: ["https://example.com/fitnessbrand"],
    viewsLastHour: 220,
    lastReviewedTimeStamp: null,
  },
  {
    name: "Gadget Launch Event",
    description: "Live coverage of new gadget launch event",
    timeStamp: Date.now(),
    budget: { min: 10000, max: 25000 },
    location: {
      type: "physical",
      name: "Berlin",
      latlong: { lat: 52.52, lng: 13.405 },
    },
    promotionType: PromotionType.LIVE_PROMOTION,
    collaborationType: CollaborationType.PAID,
    platform: SocialPlatform.YOUTUBE,
    numberOfInfluencersNeeded: 10,
    externalLinks: ["https://example.com/gadgetlaunch"],
    viewsLastHour: 500,
    lastReviewedTimeStamp: Date.now(),
  },
  {
    name: "Restaurant Chain Review",
    description: "Influencers reviewing new menu items from a popular chain",
    timeStamp: Date.now(),
    budget: { min: 300, max: 1500 },
    location: {
      type: "physical",
      name: "London",
      latlong: { lat: 51.5074, lng: -0.1278 },
    },
    promotionType: PromotionType.ADD_REVIEWS,
    collaborationType: CollaborationType.UNPAID,
    platform: SocialPlatform.FACEBOOK,
    numberOfInfluencersNeeded: 2,
    externalLinks: ["https://example.com/restaurantreview"],
    viewsLastHour: 80,
    lastReviewedTimeStamp: null,
  },
  {
    name: "Beauty Product Unboxing",
    description: "Collaborate with influencers for beauty product unboxing",
    timeStamp: Date.now(),
    budget: { min: 500, max: 2500 },
    location: {
      type: "virtual",
      name: "Global",
      latlong: null,
    },
    promotionType: PromotionType.USER_GENERATED_CONTENT,
    collaborationType: CollaborationType.PAID,
    platform: SocialPlatform.INSTAGRAM,
    numberOfInfluencersNeeded: 4,
    externalLinks: ["https://example.com/beautyunboxing"],
    viewsLastHour: 160,
    lastReviewedTimeStamp: Date.now(),
  },
  {
    name: "Local Community Event Promotion",
    description: "Promote local community events through live coverage",
    timeStamp: Date.now(),
    budget: { min: 100, max: 500 },
    location: {
      type: "physical",
      name: "Toronto",
      latlong: { lat: 43.6532, lng: -79.3832 },
    },
    promotionType: PromotionType.LIVE_PROMOTION,
    collaborationType: CollaborationType.UNPAID,
    platform: SocialPlatform.OTHERS,
    numberOfInfluencersNeeded: 1,
    externalLinks: ["https://example.com/communityevent"],
    viewsLastHour: 30,
    lastReviewedTimeStamp: null,
  },
  {
    name: "Music Festival Influencer Coverage",
    description:
      "Live coverage and story promotion of a popular music festival",
    timeStamp: Date.now(),
    budget: { min: 8000, max: 20000 },
    location: {
      type: "physical",
      name: "Los Angeles",
      latlong: { lat: 34.0522, lng: -118.2437 },
    },
    promotionType: PromotionType.STORY_PROMOTION,
    collaborationType: CollaborationType.PAID,
    platform: SocialPlatform.INSTAGRAM,
    numberOfInfluencersNeeded: 5,
    externalLinks: ["https://example.com/musicfestival"],
    viewsLastHour: 400,
    lastReviewedTimeStamp: Date.now(),
  },
];
