export const dummyGroups: any[] = [
  {
    name: "TrendSetter Brands x Influencer Impact",
    collaborationId: "gajiSpLgGzWTDZ7xSQbQ",
    userIds: ["IjOAHWjc3d8ff8u6Z2rD"],
    managerIds: ["eX3u6oniGErcE7gzdaWG"],
    latestMessage: {
      groupId: "gajiSpLgGzWTDZ7xSQbQ",
      senderId: "IjOAHWjc3d8ff8u6Z2rD",
      userType: "user",
      message: "Thanks, you too!",
      attachments: [],
      timeStamp: 1697072400000,
    },
    lastUserReadTime: [
      {
        IjOAHWjc3d8ff8u6Z2rD: 0,
      },
    ],
    lastManagerReadTime: [
      {
        eX3u6oniGErcE7gzdaWG: 0,
      },
    ],
    updatedAt: 1697071800000,
    messages: [
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message:
          "Hi! I’ve completed the first draft of the campaign post. Please review.",
        attachments: [
          {
            type: "document",
            url: "https://example.com/campaign-draft1.docx",
          },
        ],
        timeStamp: 1697040000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Got it. I’ll review the draft and get back to you shortly.",
        attachments: [],
        timeStamp: 1697040600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Thanks! Let me know if you need any changes.",
        attachments: [],
        timeStamp: 1697041200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "The draft looks good. Just a few minor adjustments needed.",
        attachments: [],
        timeStamp: 1697041800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Sure, I’ll make the adjustments and send it back.",
        attachments: [],
        timeStamp: 1697042400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Thanks! Looking forward to the updated version.",
        attachments: [],
        timeStamp: 1697043000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "I’ve updated the draft. Here’s the revised version.",
        attachments: [
          {
            type: "document",
            url: "https://example.com/campaign-draft2.docx",
          },
        ],
        timeStamp: 1697043600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "The revisions look good. We’re ready to proceed.",
        attachments: [],
        timeStamp: 1697044200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Great! I’ll prepare the post for publishing.",
        attachments: [],
        timeStamp: 1697044800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Please share the link once it’s live.",
        attachments: [],
        timeStamp: 1697045400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Will do. I’m also working on a new promotion.",
        attachments: [],
        timeStamp: 1697046000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Looking forward to it. Let me know if you need any support.",
        attachments: [],
        timeStamp: 1697046600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message:
          "Hi! I have the new promotion details ready. Can you review them?",
        attachments: [],
        timeStamp: 1697047200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Sure, send over the details.",
        attachments: [],
        timeStamp: 1697047800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Here’s the promotion brief for your review.",
        attachments: [
          {
            type: "document",
            url: "https://example.com/promotion-brief.docx",
          },
        ],
        timeStamp: 1697048400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Received. I’ll review and get back to you soon.",
        attachments: [],
        timeStamp: 1697049000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Thanks! I’m excited to hear your thoughts.",
        attachments: [],
        timeStamp: 1697049600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "The promotion looks great. Let’s proceed with the next steps.",
        attachments: [],
        timeStamp: 1697050200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Sounds good. I’ll prepare everything for launch.",
        attachments: [],
        timeStamp: 1697050800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Please keep me updated once the promotion is live.",
        attachments: [],
        timeStamp: 1697051400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message:
          "Will do! Also, I’m drafting a new blog post. Let me know if you’d like to review it.",
        attachments: [],
        timeStamp: 1697052000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "I’d be happy to review the blog post. Just send it over when ready.",
        attachments: [],
        timeStamp: 1697052600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "I’ve completed the draft of the blog post. Here’s the link.",
        attachments: [
          {
            type: "document",
            url: "https://example.com/blog-draft.docx",
          },
        ],
        timeStamp: 1697053200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Got it. I’ll review and provide feedback.",
        attachments: [],
        timeStamp: 1697053800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Thank you! Looking forward to your feedback.",
        attachments: [],
        timeStamp: 1697054400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "The blog post looks good overall. I have a few suggestions for improvement.",
        attachments: [],
        timeStamp: 1697055000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message:
          "I’ll make the suggested changes and send the updated version.",
        attachments: [],
        timeStamp: 1697055600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Perfect. Let me know once the changes are done.",
        attachments: [],
        timeStamp: 1697056200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Here’s the updated blog post. Please review.",
        attachments: [
          {
            type: "document",
            url: "https://example.com/blog-draft-updated.docx",
          },
        ],
        timeStamp: 1697056800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "The updated version looks excellent. We can go ahead with it.",
        attachments: [],
        timeStamp: 1697057400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Awesome! I’ll schedule it for publishing.",
        attachments: [],
        timeStamp: 1697058000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "Let me know once it's live. I’m also looking forward to the next campaign.",
        attachments: [],
        timeStamp: 1697058600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message:
          "I’ll keep you updated. Working on the next campaign as we speak.",
        attachments: [],
        timeStamp: 1697059200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "Great! Keep up the good work. Looking forward to seeing the new campaign details.",
        attachments: [],
        timeStamp: 1697059800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message:
          "Just finished drafting the new campaign. I’ll share it with you shortly.",
        attachments: [],
        timeStamp: 1697060400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "Looking forward to it. I’ll review it as soon as I receive it.",
        attachments: [],
        timeStamp: 1697061000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Here is the draft for the new campaign. Please review.",
        attachments: [
          {
            type: "document",
            url: "https://example.com/new-campaign-draft.docx",
          },
        ],
        timeStamp: 1697061600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Received. I’ll review and provide feedback soon.",
        attachments: [],
        timeStamp: 1697062200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Thanks! Looking forward to your feedback on this one.",
        attachments: [],
        timeStamp: 1697062800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "The campaign draft is looking good. I have a few suggestions.",
        attachments: [],
        timeStamp: 1697063400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "I’ll make those changes and get back to you.",
        attachments: [],
        timeStamp: 1697064000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Perfect. Let me know when the revised draft is ready.",
        attachments: [],
        timeStamp: 1697064600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Here’s the updated draft. Please review.",
        attachments: [
          {
            type: "document",
            url: "https://example.com/new-campaign-draft-updated.docx",
          },
        ],
        timeStamp: 1697065200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "The updated draft looks great. We’re ready to move forward.",
        attachments: [],
        timeStamp: 1697065800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Fantastic! I’ll proceed with the next steps.",
        attachments: [],
        timeStamp: 1697066400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "Excellent work. Keep me posted on the progress of the campaign.",
        attachments: [],
        timeStamp: 1697067000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Will do. I’m excited about this campaign!",
        attachments: [],
        timeStamp: 1697067600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Me too! Looking forward to seeing the results.",
        attachments: [],
        timeStamp: 1697068200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "The campaign is now live. Here’s the link: [campaign-url]",
        attachments: [],
        timeStamp: 1697068800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "I’ve checked it out. Great job! Let’s discuss the performance metrics next.",
        attachments: [],
        timeStamp: 1697069400000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Absolutely! I’ll prepare the performance metrics report.",
        attachments: [],
        timeStamp: 1697070000000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message:
          "Looking forward to it. Let’s aim to discuss it early next week.",
        attachments: [],
        timeStamp: 1697070600000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Sounds good. I’ll schedule a meeting for early next week.",
        attachments: [],
        timeStamp: 1697071200000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "eX3u6oniGErcE7gzdaWG",
        userType: "manager",
        message: "Perfect. Have a great weekend!",
        attachments: [],
        timeStamp: 1697071800000,
      },
      {
        groupId: "gajiSpLgGzWTDZ7xSQbQ",
        senderId: "IjOAHWjc3d8ff8u6Z2rD",
        userType: "user",
        message: "Thanks, you too!",
        attachments: [],
        timeStamp: 1697072400000,
      },
    ],
  },
];
