export const dummyManagers = [
    {
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        phoneNumber: "1234567890",
        location: "New York, USA",
        dateOfBirth: "1985-02-15",
        notifications: undefined,
    },
    {
        name: "Bob Smith",
        email: "bob.smith@example.com",
        phoneNumber: "0987654321",
        location: "Los Angeles, USA",
        dateOfBirth: "1978-06-23",
        notifications: undefined,
    },
    {
        name: "Carol Baker",
        email: "carol.baker@example.com",
        phoneNumber: "2345678901",
        location: "Chicago, USA",
        dateOfBirth: "1990-11-10",
        notifications: undefined,
    },
    {
        name: "David Wilson",
        email: "david.wilson@example.com",
        phoneNumber: "3456789012",
        location: "Houston, USA",
        dateOfBirth: "1983-03-28",
        notifications: undefined,
    },
    {
        name: "Eve Williams",
        email: "eve.williams@example.com",
        phoneNumber: "4567890123",
        location: "Miami, USA",
        dateOfBirth: "1995-12-05",
        notifications: undefined,
    },
];
